### ISSUE TITLE
Unknown error: No JSON object could be decoded  what exporting to strm files

### ISSUE THREAD

**Issue by klyco** [cguZZman/script.module.clouddrive.common#15] opened 2020-06-03 20:04 UTC
Hi there,

First - a HUGE Thanks for all your hard work!

I began to notice that I get the following error often when I try to export my movies in google drive:

Unknown error:
No JSON object could be decoded
Please try again.

It seems to be at random times and at random files.

This time it crashed while exporting a movie called:  Holiday Rush (2019)

Error log:

2020-06-03 13:03:07.609 T:1601164080   ERROR: [plugin.googledrive][MainThread-1601164080]: [plugin.googledrive] [1.3.4]/[1.2.15]
                                            
                                            Unknown error:
                                            No JSON object could be decoded
                                            Please try again.
                                            
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py", line 772, in route
                                                method(**arguments)
                                              File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py", line 387, in _run_export
                                                self.__export_folder(driveid, item, export_folder, export, export_items_info, item_id)
                                              File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py", line 434, in __export_folder
                                                self.__export_folder(driveid, item, folder_path, export, items_info, root_id)
                                              File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/ui/addon.py", line 417, in __export_folder
                                                items = self.get_provider().get_folder_items(Utils.default(Utils.get_safe_value(folder, 'drive_id'), driveid), folder['id'])
                                              File "/storage/.kodi/addons/plugin.googledrive/resources/lib/provider/googledrive.py", line 157, in get_folder_items
                                                files = provider_method(url, parameters = parameters)
                                              File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/remote/oauth2.py", line 105, in get
                                                return self.request('get', path, **kwargs)
                                              File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/remote/oauth2.py", line 102, in request
                                                return self.prepare_request(method, path, parameters, request_params, access_tokens, headers).request_json()
                                              File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/remote/oauth2.py", line 92, in prepare_request
                                                access_tokens = self.get_access_tokens()
                                              File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/remote/provider.py", line 69, in get_access_tokens
                                                return self._account_from_manager()['access_tokens']
                                              File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/remote/provider.py", line 60, in _account_from_manager
                                                self._account_manager.load()
                                              File "/storage/.kodi/addons/script.module.clouddrive.common/clouddrive/common/account.py", line 47, in load
                                                self.accounts = json.loads(fo.read())
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            
                                            
                                            show_error_dialog: True

**Comment by cguZZman** [comment] 2020-06-10 17:14
Thanks for reporting the issue, this is a duplicate of https://github.com/cguZZman/plugin.googledrive/issues/76
Please read the workaround in there to fix it.

**Closed as completed by cguZZman** 2020-06-10 17:14 UTC
